feat: 포착하기 기능 구현
Nexters/phochak-server pull request #32
Opened 2023-01-30 12:03 UTC by JinuCheon

❗️ 이슈 번호
close #26 

📝 구현 내용
포착하기 및 포착 취소하기 기능 구현했습니다.
포착하기: `POST /v1/post/{postId}/phochak`
포착 취소하기: `DELETE /v1/post/{postId}/phochak`

<img width="1411" alt="스크린샷 2023-01-30 오후 8 59 53" src="https://user-images.githubusercontent.com/76773202/215471194-a4b502f5-9cd3-43d7-a71f-e356e1f13798.png">

🙇🏻‍♂️ 리뷰어에게 부탁합니다!
### 이슈
도메인 이름을 Phochak 으로 했더니, intellij가 application 이름과 헷갈려서 가~끔 정신을 못차리는 일이 발생합니다.
refactor 기능이나 자동생성 기능 사용했을때 종종 발생하는데, 혹시 추가적인 이슈가 있다면 like 나 bookmark로 변경하면 좋을 것 같습니다.

💡 참고 자료
(없다면 지워도 됩니다!)

2023-01-30 14:53 UTC, seyoung755 approved these changes, later dismissed

2023-01-30 14:53 UTC, seyoung755 commented on src/test/java/com/nexters/phochak/controller/PhochakControllerTest.java
> +@ExtendWith(SpringExtension.class)
`@SpringBootTest` 있으면 요건 떼도 괜찮습니다~

2023-01-30 14:53 UTC, seyoung755 commented on src/main/java/com/nexters/phochak/repository/UserRepository.java
> +    Optional<User> findOneByNickname(String nickname);
보통 query method 컨벤션상 findBy를 많이써서 findByNickname으로 수정하면 어떨까 싶네요

2023-01-30 14:53 UTC, seyoung755 commented on src/main/java/com/nexters/phochak/repository/PhochakRepository.java
> +    Optional<Phochak> findOneByUserAndPost(User user, Post post);
요기도 One 지우는거 어떨까요

2023-01-30 14:54 UTC, seyoung755 commented
고생하셨습니다 👍

2023-01-30 15:02 UTC, JinuCheon commented on src/test/java/com/nexters/phochak/controller/PhochakControllerTest.java
> +@ExtendWith(SpringExtension.class)
아! 제가 짠 컨트롤러 코드가 mocking 없는 통합 테스트라서 붙여야 할 것 같습니다.
전에 회의할 때 컨트롤러 테스트는 통합테스트로 진행해도 좋을 것 같다고 얘기를 했었는데,
컨트롤러도 mocking으로 할까요?

2023-01-30 15:03 UTC, JinuCheon commented on src/main/java/com/nexters/phochak/repository/UserRepository.java
> +    Optional<User> findOneByNickname(String nickname);
그렇군요. 단건 조회에 전부 one을 붙였었는데..
한 개 이상 조회되면 JPA에서 지정한 exception 발생해서 괜찮다고 생각했었습니다 :)

2023-01-30 15:06 UTC, JinuCheon commented on src/main/java/com/nexters/phochak/repository/UserRepository.java
> +    Optional<User> findOneByNickname(String nickname);
정정 완료 했습니다!

2023-01-31 00:20 UTC, seyoung755 commented on src/main/java/com/nexters/phochak/repository/UserRepository.java
> +    Optional<User> findOneByNickname(String nickname);
헛 One으로 쓰면 그런 차이점이 있나요?? 몰랐습니다 ㄷㄷ;;

2023-01-31 00:21 UTC, seyoung755 commented on src/test/java/com/nexters/phochak/controller/PhochakControllerTest.java
> +@ExtendWith(SpringExtension.class)
아 드래그가 좀 잘못됐는데
ExtendWith(SpringExtension)만 말한거였어요!
요 어노테이션이 SpringbootTest에 포함돼있습니다

2023-01-31 02:42 UTC, JinuCheon commented
https://stackoverflow.com/questions/45988295/difference-between-findby-and-findoneby-in-spring-data-jpa

이것저것 문서를 찾아보니, 이런 논쟁이 있네요.

JPA 공식 문서에서도 `findOneBy~` 로 쓰는 예제가 있는데, 관련해서 따로 설명들이 없네요.


### 테스트 결과
`findBy~` 와 `findOneBy~` 는 똑같은 동작을 하는 것 같습니다.

**그냥 return type에 따라 달라지더군요.**

return type이 `Optional<T>` 일때 : 결과가 2개 이상이면 `IncorrectResultSizeDataAccessException` 을 발생시킵니다.
- `getSingleResult` 이 적용되는 것 같습니다.

return type이 `List<T>` 일때 : 2개 이상의 결과도 동일하게 조회 됩니다.
- `getResultList` 이 적용되는 것 같습니다.

---
### 결론
위 stackoverflow에서 2020년 마지막 댓글에서 말하는 'find 와 by 사이의 단어는 무시한다'가 맞는 말인 것 같아요.(내부 구현도 그래보이고..)

번외로 여러건 조회(`List<T>`)를 위해 `findAllBy~` 로 쓰는 사람들도 있네요.
테스트 결과로 봤을때 All은 무시될텐데 말이죠?!

_혹시 가독성을 위해 저런식으로 one, all을 붙여서 네이밍을 한건가.._
_다른 추측은, typeORM 에서 `findOneBy`로 문법을 써서, 사람들이 헷갈렸을지도.._
_JPA 공식 문서에 예제에서는 왜 `findOneBy~`를 사용했을까.._

2023-01-31 02:44 UTC, JinuCheon commented on src/test/java/com/nexters/phochak/controller/PhochakControllerTest.java
> +@ExtendWith(SpringExtension.class)
정정했습니다 감사합니다!

2023-01-31 13:15 UTC, seyoung755 commented
@JinuCheon 
오... 깊게 탐구해보셨군요 ㅋㅋㅋ 몰랐던 사실 배워갑니다 ㅋㅋㅋㅋ
findAllBy 이런건 사용했던 기억이 있는데 결국은 리턴 타입이 결정하는 것이군요..

2023-01-31 13:15 UTC, seyoung755 approved these changes

2023-01-31 13:39 UTC, seyoung755 requested changes

2023-01-31 13:39 UTC, seyoung755 commented on src/main/java/com/nexters/phochak/service/impl/PhochakServiceImpl.java
> +import javax.transaction.Transactional;
요거 javax 보다 springframework 걸 좀 더 많이 쓰지 않나요??

2023-01-31 15:40 UTC, JinuCheon commented on src/main/java/com/nexters/phochak/service/impl/PhochakServiceImpl.java
> +import javax.transaction.Transactional;
아. 그렇군요!
옵션 부분에서 패키지마다 차이점이 있었군요.
감사합니다

2023-02-01 01:47 UTC, seyoung755 approved these changes

2023-02-01 03:07 UTC, merged